version: "3.8"

networks:
  rabbitmq_go_net:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq1
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_go_net

  producer:
    build: 
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - rabbitmq_go_net

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - app_network
