version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER=admin
      RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app_network

  producer:
    build: 
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - app_network

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: overlay